import Sidebar from "@/components/shared/SideBar/Sidebar";
import "../styles/index.css";

export const metadata = {
  title: "NurAdmin Dashboard-Nextjs",
  description: "Generated by Nurit",
};

export default function RootLayout({ children }) {
  return (
  
      <div className="flex h-screen overflow-hidden">
        {/* sidebar start here  */}
        <Sidebar />
        {/* content aria  */}
        <div className="relative flex flex-1 flex-col overflow-y-auto overflow-x-hidden">
          {/* <Navbar /> */}
          <main>{children}</main>
        </div>
      </div>
   
  );
}
